### ISSUE TITLE
Support OneTimeSetUp & OneTimeTearDown attributed functions

### ISSUE THREAD

**Issue by stakemura** [Cysharp/RuntimeUnitTestToolkit#10]
Would you like to support OneTimeSetUp & OneTimeTearDown attributed functions?
I know I should provide the patch.
But it is too heavy for me. sorry...

**Comment by neuecc** [comment]
Thank you for your request.
First of all, it would be good if the following could be.

///

Already supported

* SetUp
* TearDown
* Test
* UnityTest
* TestCase
* TestCaseSource

NUnit Attributes

* OneTimeSetUp
* OneTimeTearDown
* SetUpFixture

Unity Attributes

* UnitySetUp
* UnityTearDown
* PrebuildSetup
* PostBuildCleanup

**Comment by neuecc** [comment]
I've released 2.4.0, it supports these attribute(without PrebuildSetup/PostBuildCleanup).
Please try it.
