### ISSUE TITLE
Support macOS test runner

### ISSUE THREAD

**Issue by stakemura** [Cysharp/RuntimeUnitTestToolkit#7]
@neuecc 
RuntimeUnitTestToolkit fails to run BuildRunTest on macOS due to lack of file extension `.app`.
I prepared PR #6 for resolve this case.

Unfortunately, Unity's BuildPipeline.BuildPlayer under `headless mode` doesn't seem to work on macOS, regardless of the file extension. If you have any idea, please let me know.

PS: Thank you for commit !

**Comment by stakemura** [comment]
I thought Unity's BuildPipeline.BuildPlayer under headless mode doesn't work on macOS.
In fact, it is working.
Unlike Linux or Windows, macOS test runner doesn't show any log messages. Therefore I misunderstood.

**Comment by neuecc** [comment]
If it doesn't output log, then that's a problem (can't know the test results!)
Now using `Console.WriteLine`, but if it doesn't work in macos-headless, 
I'll add an option to turn it into an output via `Debug.Log`, how about that?

**Comment by stakemura** [comment]
Thank you for your comment.
Unfortunately, Unlike Linux or Windows, macOS Unity couldn't export a **console application** and acts as a GUI application even under headless mode. So I guess the play-mode test code is required to export log files for CI purpose.

**Comment by neuecc** [comment]
Thanks, I've understood it.

Is ExitCode works?
If so, I'll add -log(filePath) option and output to file,
after running .app, cat logs will be similar as other os.

**Comment by stakemura** [comment]
I tried the following code on Unity 2018.4.12f1.

```
        [Test]
        public void TestSimplePasses()
        {
            Assert.Fail("assert");
        }
```

```
/Applications/Unity/Hub/Editor/2018.4.12f1/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath **** -executeMethod UnitTestBuilder.BuildUnitTest /headless /ScriptBackend Mono2x /BuildTarget StandaloneOSX
```
```
open ****/test.app --args -batchmode
echo "exit code: $?"
> exit code: 0
```

OMG. ExitCode doesn't seem to work...

**Comment by guitarrapc** [comment]
How about calling execution file directly from terminal?

You know, `.app` is just a macOS app symbol but shell can call it's binary like this. Both stdout and stderr wil show on terminal and can handle with pipe.

```shell
./test.app/Contents/MacOS/RuntimeUnitTestToolkit
```
 
![image](https://user-images.githubusercontent.com/3856350/80464638-0f5aa880-8975-11ea-82d4-062d87d94716.png)

Isn't it sufficient for CI or headless usage?

**Comment by guitarrapc** [comment]
Here's exit code result. Exitcode 0 on success and 1 if failed.

![image](https://user-images.githubusercontent.com/3856350/80465578-3f567b80-8976-11ea-98d8-fbbcc3f5976c.png)

![image](https://user-images.githubusercontent.com/3856350/80465456-1df58f80-8976-11ea-80fe-1b944bd7aecf.png)

**Comment by guitarrapc** [comment]
You can find Pipe works without trouble.

```shell
$ ./test.app/Contents/MacOS/RuntimeUnitTestToolkit | grep NG
[NG]TestSimplePasses, NUnit.Framework.AssertionException: assert
Test Failed, please see [NG] log.
```

**Comment by stakemura** [comment]
@guitarrapc I really appreciate your helpful comments!!! I'm glad I asked here.

**Comment by guitarrapc** [comment]
thank you for detail report, I've added note to README.

> https://github.com/Cysharp/RuntimeUnitTestToolkit#how-to-get-stdoutstderr--exitcode-with-standaloneosx-wheadless
