### ISSUE TITLE
Proposal: Modify iOS output folder

### ISSUE THREAD

**Issue by stakemura** [Cysharp/RuntimeUnitTestToolkit#9]
In the current implementation, iOS output folder is different from the other build targets.

* iOS
 `./bin/UnitTest/iOS_***/test/`
* the other build targets
 `./bin/UnitTest/***_***/test.***`

I want to modify `UnitTestBuilder.BuildUnitTest()' as follows.

```
 buildPath = $"bin/UnitTest/{settings.BuildTarget}_{settings.ScriptBackend}";
 if (settings.BuildTarget != BuildTarget.iOS)
 {
     buildPath += "/test" + GetExtensionForBuildTarget(settings.BuildTarget);
 }
```

If you don't mind, I will send PR.

**Comment by neuecc** [comment]
Does this mean that it becomes a folder in the case of iOS, while it becomes a file name except iOS?
There may be a similar case for something other than iOS (e.g. WebGL?). .
If the rules for special handling are increased, it will become difficult to understand, so I think it's fine to keep it as it is.
What do you think?

**Comment by stakemura** [comment]
I agree to your opinion.
A platform-specific handling is devil in this situation.
I'll use /buildPath option to change output folder.
Thanks.
